apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: github-runner-autoscaler
  namespace: actions-runner-system
spec:
  scaleTargetRef:
    name: github-runner-deployment
  minReplicas: 0
  maxReplicas: 20
  metrics:
    - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
      repositoryNames:
        - khalifa7867/aws_gcp_infra_provisioning-project
  scaleDownDelaySecondsAfterScaleOut: 300
